config/routes.rb
Rails.application.routes.draw do
  
  get 'user_sessions/new'

  get 'user_sessions/create'

  get 'user_sessions/destroy'

  get 'forms' => 'forms#show'
  get 'forms/edit' => 'forms#edit'
  patch 'forms' => 'forms#show'

  get 'users/edit' => 'users#edit'

  get 'users/:id/quality_of_life' => 'users#quality_of_life'
  patch 'users/:id/quality_of_life' => 'users#update'

  resources :users
  resources :forms

  root 'users#index'
  resources :user_sessions
  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

end

app/models/form.rb
class Form < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	authenticates_with_sorcery!

	validates :password, length: { minimum: 7 }
	validates :password, confirmation: true
	validates :password_confirmation, presence: true

	validates :email, uniqueness: true

	has_one :form, dependent: :destroy


	def logged_in? 
		@user
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :require_login

  private
  def not_authenticated
  	redirect_to login_path, alert: "Please login first"
  end 
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
	def index 
		@form = Form.compile_form
		redirect_to @form
	end

	def new
		#Makes a new form, but does not save to database
		@form = Form.new
	end

	def create
		#Makes and saves new form to database
		@form = Form.new(form_params)
		@form.user_id = current_user.id
		@form.save

		respond_to do |format|
			if @form.save
				format.html { redirect_to @form, notice: 'Form was successfully created.' }
				format.json { render :show, status: :created, location: @form }
			else
				format.html { render :new }
				format.json { render json: @form.errors, status: :unprocessable_entity }
			end
		end
	end

	def show
		@form = Form.find(params[:id])
	end

	def update
		@form = Form.find(params[:id])
		respond_to do |format|
			if @form.update(form_params)
		    	format.html { redirect_to @form, notice: 'Form was successfully updated.' }
		    	format.json { render :show, status: :ok, location: @form }
			else
		    	format.html { render :edit }
		    	format.json { render json: @form.errors, status: :unprocessable_entity }
		  	end
		end
	end

	def destroy
		#Destroys form
		@form.destroy
		respond_to do |format|
		  format.html { redirect_to users_url, notice: 'Form was successfully destroyed.' }
		  format.json { head :no_content }
		end
	end


	private
		#Defines which parameters can be passed into the database
		def form_params
			params.require(:form).permit(:user_id, :gh_ami_cc_only, :gh_ami_cc_plus, :gh_ami_reg_med, :gh_ami_invasive, :gh_ami_respirator, :gh_ami_dialysis, :gh_ami_cpr,:gh_bi_cc_only, :gh_bi_cc_plus, :gh_bi_reg_med, :gh_bi_invasive, :gh_bi_respirator, :gh_bi_dialysis, :gh_bi_cpr,:dh_ami_cc_only, :dh_ami_cc_plus, :dh_ami_reg_med, :dh_ami_invasive, :dh_ami_respirator, :dh_ami_dialysis, :dh_ami_cpr,:dh_bi_cc_only, :dh_bi_cc_plus, :dh_bi_reg_med, :dh_bi_invasive, :dh_bi_respirator, :dh_bi_dialysis, :dh_bi_cpr, :esmc_ami_cc_only, :esmc_ami_cc_plus, :esmc_ami_reg_med, :esmc_ami_invasive, :esmc_ami_respirator, :esmc_ami_dialysis, :esmc_ami_cpr,:esmc_bi_cc_only, :esmc_bi_cc_plus, :esmc_bi_reg_med, :esmc_bi_invasive, :esmc_bi_respirator, :esmc_bi_dialysis, :esmc_bi_cpr, :nhi_ami_cc_only, :nhi_ami_cc_plus, :nhi_ami_reg_med, :nhi_ami_invasive, :nhi_ami_respirator, :nhi_ami_dialysis, :nhi_ami_cpr, :nhi_bi_cc_only, :nhi_bi_cc_plus, :nhi_bi_reg_med, :nhi_bi_invasive, :nhi_bi_respirator, :nhi_bi_dialysis, :nhi_bi_cpr)
		end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :require_login, except: [:destroy]
  def new
  	@user = User.new
  end

  def create
    #Logs in user
  	if @user = login(params[:email], params[:password])
  		redirect_back_or_to(:users, notice: 'Login successful')
  	else
  		flash.now[:alert] = 'Login failed'
  		render action: 'new'
  	end
  end

  def destroy
    #Logs out user
  	logout
  	redirect_to(:users, notice: 'Logged out!')

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_filter :require_login, only: [:index, :new, :create]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        auto_login(@user)
        format.html { redirect_to new_form_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to :users, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def form

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name, :quality_of_life)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/first_scenarios/_form.html.erb
<%= form_for(@first_scenario) do |f| %>

  <div class="field">
    <p><strong>1. My quality of health is similar to what it is now. i.e. I have no end-stage medical conditions and my mental faculties are intact. I am able to care for myself.</strong></p>
    <p>If I develop an acute medical illness that may be treated, and my doctors think I have a reasonable chance of surviving the illness and leaving the hospital, I wish the following: (Check any that apply:</p>
    <%= f.check_box :ami_cc_only %>Comfort care only <br />
    <%= f.check_box :ami_cc_plus,checked_value: "1",unchecked_value: "0" %>Comfort care, to include intravenous fluids and tube feedings<br />
    <%= f.check_box :ami_reg_med %>Regular medical care <br />
    <%= f.check_box :ami_invasive,checked_value: "1",unchecked_value: "0" %>Invasive procedures like surgery or heart catheterizations<br />
    <%= f.check_box :ami_respirator,checked_value: "1",unchecked_value: "0" %>Temporary support from a respirator<br />
    <%= f.check_box :ami_dialysis,checked_value: "1",unchecked_value: "0" %>Temporary support<br />
    <%= f.check_box :ami_cpr,checked_value: "1",unchecked_value: "0" %>CPR if my heart stops<br />
  </div>
  <div class="field">
    <p>If I suffer some form of brain injury (stroke, bleeding, cardiac arrest, etc.) that makes it unlikely I’ll ever regain the ability to make decisions for myself, I wish the following: (Check any that apply):</p>
    <%= f.check_box :bi_cc_only %>Comfort care only <br />
    <%= f.check_box :bi_cc_plus %>Comfort care, to include intravenous fluids and tube feedings<br />
    <%= f.check_box :bi_reg_med %>Regular medical care <br />
    <%= f.check_box :bi_invasive %>Invasive procedures like surgery or heart catheterizations<br />
    <%= f.check_box :bi_respirator %>Temporary support from a respirator<br />
    <%= f.check_box :bi_dialysis %>Temporary support<br />
    <%= f.check_box :bi_cpr %>CPR if my heart stops<br />
  </div>
  <div class="actions">
    <%= f.submit "Submit First Scenario" %>
  </div>

<% end %>

app/views/first_scenarios/edit.html.erb
edit.html.erb

app/views/first_scenarios/index.html.erb
<%= render 'form' %>

app/views/first_scenarios/new.html.erb
new.html.erb

app/views/forms/_form.html.erb
<!-- Form for the Living Will  -->
<%= form_for(@form) do |f| %>

  <div id="first">
    <div class="field">

      <p><h4><strong>1. My quality of health is similar to what it is now. i.e. I have no end-stage medical conditions and my mental faculties are intact. I am able to care for myself.</strong></h4></p>

      <p>If I develop an acute medical illness that may be treated, and my doctors think I have a reasonable chance of surviving the illness and leaving the hospital, I wish the following: (Check any that apply:</p>
      <%= f.check_box :gh_ami_cc_only %>Comfort care only <br />
      <%= f.check_box :gh_ami_cc_plus,checked_value: "1",unchecked_value: "0" %>Comfort care, to include intravenous fluids and tube feedings<br />
      <%= f.check_box :gh_ami_reg_med %>Regular medical care <br />
      <%= f.check_box :gh_ami_invasive,checked_value: "1",unchecked_value: "0" %>Invasive procedures like surgery or heart catheterizations<br />
      <%= f.check_box :gh_ami_respirator,checked_value: "1",unchecked_value: "0" %>Temporary support from a respirator<br />
      <%= f.check_box :gh_ami_dialysis,checked_value: "1",unchecked_value: "0" %>Temporary support<br />
      <%= f.check_box :gh_ami_cpr,checked_value: "1",unchecked_value: "0" %>CPR if my heart stops<br />
    </div>
    <div class="field">
      <p>If I suffer some form of brain injury (stroke, bleeding, cardiac arrest, etc.) that makes it unlikely I’ll ever regain the ability to make decisions for myself, I wish the following: (Check any that apply):</p>
      <%= f.check_box :gh_bi_cc_only %>Comfort care only <br />
      <%= f.check_box :gh_bi_cc_plus %>Comfort care, to include intravenous fluids and tube feedings<br />
      <%= f.check_box :gh_bi_reg_med %>Regular medical care <br />
      <%= f.check_box :gh_bi_invasive %>Invasive procedures like surgery or heart catheterizations<br />
      <%= f.check_box :gh_bi_respirator %>Temporary support from a respirator<br />
      <%= f.check_box :gh_bi_dialysis %>Temporary support<br />
      <%= f.check_box :gh_bi_cpr %>CPR if my heart stops<br />
    </div>
    <div class="container-fluid">
            
      <span id="to_2" class="next-button"> Next </span>
    </div>
  </div>
  <div class="hidden" id="second">
    <div class="field">

      <p><h4><strong>2. My general health has deteriorated to the point I need assistance in caring for myself but I am still at home and my mental faculties are intact.</strong></h4></p>

      <p>If I develop an acute medical illness that may be treated, and my doctors think I have a reasonable chance of surviving the illness and leaving the hospital, I wish the following: (Check any that apply:</p>
      <%= f.check_box :dh_ami_cc_only %>Comfort care only <br />
      <%= f.check_box :dh_ami_cc_plus %>Comfort care, to include intravenous fluids and tube feedings<br />
      <%= f.check_box :dh_ami_reg_med %>Regular medical care <br />
      <%= f.check_box :dh_ami_invasive %>Invasive procedures like surgery or heart catheterizations<br />
      <%= f.check_box :dh_ami_respirator %>Temporary support from a respirator<br />
      <%= f.check_box :dh_ami_dialysis %>Temporary support<br />
      <%= f.check_box :dh_ami_cpr %>CPR if my heart stops<br />
    </div>
    <div class="field">
      <p>If I suffer some form of brain injury (stroke, bleeding, cardiac arrest, etc.) that makes it unlikely I’ll ever regain the ability to make decisions for myself, I wish the following: (Check any that apply):</p>
      <%= f.check_box :dh_bi_cc_only %>Comfort care only <br />
      <%= f.check_box :dh_bi_cc_plus %>Comfort care, to include intravenous fluids and tube feedings<br />
      <%= f.check_box :dh_bi_reg_med %>Regular medical care <br />
      <%= f.check_box :dh_bi_invasive %>Invasive procedures like surgery or heart catheterizations<br />
      <%= f.check_box :dh_bi_respirator %>Temporary support from a respirator<br />
      <%= f.check_box :dh_bi_dialysis %>Temporary support<br />
      <%= f.check_box :dh_bi_cpr %>CPR if my heart stops<br />
    </div>

    <div class="container-fluid">
            <span id="back_to_1" class="back-button"> Back </span>
            <span id="to_3" class="next-button"> Next </span>
    </div>

  </div>

  <div class="hidden" id="third">
    <div class="field">

      <p><h4><strong>3. I have been diagnosed with an end-stage medical condition but have been told I could live for a year or more. I still live at home and my mental faculties are intact.</strong></h4></p>

      <p>If I develop an acute medical illness that may be treated, and my doctors think I have a reasonable chance of surviving the illness and leaving the hospital, I wish the following: (Check any that apply:</p>
      <%= f.check_box :esmc_ami_cc_only %>Comfort care only <br />
      <%= f.check_box :esmc_ami_cc_plus %>Comfort care, to include intravenous fluids and tube feedings<br />
      <%= f.check_box :esmc_ami_reg_med %>Regular medical care <br />
      <%= f.check_box :esmc_ami_invasive %>Invasive procedures like surgery or heart catheterizations<br />
      <%= f.check_box :esmc_ami_respirator %>Temporary support from a respirator<br />
      <%= f.check_box :esmc_ami_dialysis %>Temporary support<br />
      <%= f.check_box :esmc_ami_cpr %>CPR if my heart stops<br />
    </div>
    <div class="field">
      <p>If I suffer some form of brain injury (stroke, bleeding, cardiac arrest, etc.) that makes it unlikely I’ll ever regain the ability to make decisions for myself, I wish the following: (Check any that apply):</p>
      <%= f.check_box :esmc_bi_cc_only %>Comfort care only<br />
      <%= f.check_box :esmc_bi_cc_plus %>Comfort care, to include intravenous fluids and tube feedings<br />
      <%= f.check_box :esmc_bi_reg_med %>Regular medical care<br /> 
      <%= f.check_box :esmc_bi_invasive %>Invasive procedures like surgery or heart catheterizations<br />
      <%= f.check_box :esmc_bi_respirator %>Temporary support from a respirator<br />
      <%= f.check_box :esmc_bi_dialysis %>Temporary support<br />
      <%= f.check_box :esmc_bi_cpr %>CPR if my heart stops<br />
    </div>

    <div class="container-fluid">
      <span id="back_to_2" class="back-button"> Back </span>
      <span id="to_4" class="next-button"> Next </span>
    </div>

  </div>

  <div class="hidden" id="fourth">
    <div class="field">

      <p><h4><strong>4. I am dying from an end-stage medical condition with no hope of improvement.</strong></h4></p>

      <p>If I develop an acute medical illness that may be treated, and my doctors think I have a reasonable chance of surviving the illness and leaving the hospital, I wish the following: (Check any that apply:</p>
      <%= f.check_box :nhi_ami_cc_only %>Comfort care only<br /> 
      <%= f.check_box :nhi_ami_cc_plus %>Comfort care, to include intravenous fluids and tube feedings<br />
      <%= f.check_box :nhi_ami_reg_med %>Regular medical care<br /> 
      <%= f.check_box :nhi_ami_invasive %>Invasive procedures like surgery or heart catheterizations<br />
      <%= f.check_box :nhi_ami_respirator %>Temporary support from a respirator<br />
      <%= f.check_box :nhi_ami_dialysis %>Temporary support<br />
      <%= f.check_box :nhi_ami_cpr %>CPR if my heart stops<br />
    </div>
    <div class="field">
      <p>If I suffer some form of brain injury (stroke, bleeding, cardiac arrest, etc.) that makes it unlikely I’ll ever regain the ability to make decisions for myself, I wish the following: (Check any that apply):</p>
      <%= f.check_box :nhi_bi_cc_only %>Comfort care only <br />
      <%= f.check_box :nhi_bi_cc_plus %>Comfort care, to include intravenous fluids and tube feedings<br />
      <%= f.check_box :nhi_bi_reg_med %>Regular medical care <br />
      <%= f.check_box :nhi_bi_invasive %>Invasive procedures like surgery or heart catheterizations<br />
      <%= f.check_box :nhi_bi_respirator %>Temporary support from a respirator<br />
      <%= f.check_box :nhi_bi_dialysis %>Temporary support<br />
      <%= f.check_box :nhi_bi_cpr %>CPR if my heart stops<br />
    </div>
    <div class="container-fluid">
      <span id="back_to_3" class="back-button"> Back </span>
      <button class="button-override float-right">Finish</button>
    </div>
  </div>
<% end %>

app/views/forms/edit.html.erb
<h1>Edit Form</h1>

<div class="progress">
  <div class="progress-bar" role="progressbar" aria-valuenow="70"
  aria-valuemin="0" aria-valuemax="100" style="width:0%">
    
  </div>
</div>

<% @form = Form.find(params[:id]) %>

<%= render 'form' %>

<script>
	$(function() {
		form_change();
	});
</script>

app/views/forms/new.html.erb
<h3><strong>My wishes for medical care at the end of my life</strong></h3>

<div class="progress">
  <div class="progress-bar" role="progressbar" aria-valuenow="70"
  aria-valuemin="0" aria-valuemax="100" style="width:0%">
    
  </div>
</div>


<%= render 'form' %>

<script>
	// $(function() {
	// 	form_change();
	// })
</script>

app/views/fourth_scenarios/edit.html.erb
edit.html.erb

app/views/fourth_scenarios/index.html.erb
<%= render 'form' %>

app/views/fourth_scenarios/new.html.erb
new.html.erb

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Easy Living Wills</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1">


</head>
<body>

  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Things to remember as you fill out this Living Will</h4>
        </div>
        <div class="modal-body">
          <p>- Your living will is mainly used if you are unable to tell your doctors what care you want to receive at the time they need to know your wishes.  If you are able to discuss your condition with your doctors and decide what care you want to receive you will simply tell them what your wishes are.</p>
          
          <p>- <strong>For a person to safely decide the care they want to receive they must have Decision-making Capacity</strong>.  This means they must be able to understand the information their health care providers tell them and are able to use this information to make an informed decision about the medical care they want.</p>

          <p>- Many people suffer from conditions that prevent them from having capacity.  This would include conditions like mental illness, dementia, severe learning disabilities and brain damage (strokes, brain trauma, etc.).  These conditions are often times permanent and the person may never be able to make their own health care decisions.</p>

          <p>- Some people may temporarily lose capacity if they become acuity ill, especially if they are sick enough to require hospitalization.  This can be a result of the illness itself.  Examples would be things like severe infections and acute strokes.  Loss of capacity can also result from the treatment for the acute illness, in particular medications.  Often times in these situations the person will regain the capacity to make their own decisions as they recover from the illness.</p>

          <p>- If you are unable to tell your doctors what care you would want to receive they will look to your living will for guidance.  It is important to realize that a written living will can’t possibly prepare for all medical decisions that might have to be made for you.</p>

          <p>- The best plan for making sure you receive the care you would want if you aren’t able to tell your doctors yourself is to pick someone to be your Medical Power of Attorney (MPOA).  An MPOA is the person you have legally designated to make your medical decisions for you if you temporarily or permanently lose capacity. Your MPOA can make any health care decision for you that you would make for yourself.</p>

          <p>- Your MPOA can use your living will to help them decide what care you would want to receive given your medical situation.  But it is important that you talk with your MPOA while you still have capacity and discuss the common decisions that may have to be made near the end of your life.  You can also use this living will to guide these talks with your MPOA.</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
          <a class="navbar-brand" href="#">
            <img class="brandImage" alt="CAMC brand" src="http://sites.middlebury.edu/thekeystodanbrownsinferno/files/2013/10/caduceus.jpg">        
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">

            <% if current_user %>
              <li class="active"><%= link_to "Logout", :logout, method: :post %></li>
              <li class="active"><%= link_to "Edit Will", edit_form_path(current_user.id) %></li>
              <li class="active"><a href="#" data-toggle="modal" data-target="#myModal">Things to Remember</a></li>
            <% else %>
              <li class="active"><%= link_to "Register", new_user_path %></li>
              <li class="active"><%= link_to "Login", :login %></li>
            <% end %>
            
        </ul>
        
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>


  <div>
    <p class="header-text" id="notice"><%= flash[:notice] %></p>
    <p class="header-text" id="alert"><%= flash[:alert] %></p>
  </div>
  
  <div class="main-form-box">		
	  <%= yield %>
  </div>

  <script>
    $(document).ready(initialize);
    $(document).on('page:load', initialize);

  </script>

</body>
</html>

app/views/second_scenarios/edit.html.erb
edit.html.erb

app/views/second_scenarios/index.html.erb
<%= render 'form' %>

app/views/second_scenarios/new.html.erb
new.html.erb

app/views/third_scenarios/edit.html.erb
edit.html.erb

app/views/third_scenarios/index.html.erb
<%= render 'form' %>

app/views/third_scenarios/new.html.erb
new.html.erb

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<h1 id="starting" class="header-text">Let's Get Started!</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<div id="intro-text">
	<h3 class="header-text">Here are some things to remember as you fill out this Living Will</h3>
	<p>- Your living will is mainly used if you are unable to tell your doctors what care you want to receive at the time they need to know your wishes.  If you are able to discuss your condition with your doctors and decide what care you want to receive you will simply tell them what your wishes are.</p>

	<p>- <strong>For a person to safely decide the care they want to receive they must have Decision-making Capacity</strong>.  This means they must be able to understand the information their health care providers tell them and are able to use this information to make an informed decision about the medical care they want.</p>

	<p>- Many people suffer from conditions that prevent them from having capacity.  This would include conditions like mental illness, dementia, severe learning disabilities and brain damage (strokes, brain trauma, etc.).  These conditions are often times permanent and the person may never be able to make their own health care decisions.</p>

	<p>- Some people may temporarily lose capacity if they become acuity ill, especially if they are sick enough to require hospitalization.  This can be a result of the illness itself.  Examples would be things like severe infections and acute strokes.  Loss of capacity can also result from the treatment for the acute illness, in particular medications.  Often times in these situations the person will regain the capacity to make their own decisions as they recover from the illness.</p>

	<p>- If you are unable to tell your doctors what care you would want to receive they will look to your living will for guidance.  It is important to realize that a written living will can’t possibly prepare for all medical decisions that might have to be made for you.</p>

	<p>- The best plan for making sure you receive the care you would want if you aren’t able to tell your doctors yourself is to pick someone to be your Medical Power of Attorney (MPOA).  An MPOA is the person you have legally designated to make your medical decisions for you if you temporarily or permanently lose capacity. Your MPOA can make any health care decision for you that you would make for yourself.</p>

	<p>- Your MPOA can use your living will to help them decide what care you would want to receive given your medical situation.  But it is important that you talk with your MPOA while you still have capacity and discuss the common decisions that may have to be made near the end of your life.  You can also use this living will to guide these talks with your MPOA.</p>
	<div class="container-fluid">
	  <span class="back-button"> Back </span>
	  <!-- <span id="intro-next" class="next-button"> Next </span> -->
	  <button class="button-override float-right"><%= link_to 'Begin', new_form_path %></button></br>
	</div>
	 
</div>

<div class="hidden" id="start-form">
	<h3 class="header-text">Click the link below to continue to the Living Will Form.</h3><br>
		
  	<div class="container-fluid middle">
      
      <button class="button-override"><%= link_to 'Begin', new_user_path %></button></br>
  	</div>

</div>

  

app/views/users/intro.html.erb
intro.html.erb

app/views/users/new.html.erb
<% if logged_in? %>
	<h1 class="header-text">Welcome <% @user.first_name %></h1>

	<h3 class="header-text">Do you need to edit your profile?</h3>
	<button class="header-text"><%= link_to 'Edit Profile', edit_user_path(current_user.id) %></button>
	

<% else %>
	<h1 class="header-text">New User</h1>
	<%= render 'form' %>
<% end %>